name: EZPolitics
favicon: null
layout_spectrum: 0.83758
typography_spectrum: 0.2168975984677672
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Politics Made EZ!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#ba0000'
    - '#2b24ad'
    - '#6772f0'
    - '#450000'
  brandStrength: 0.6589674537535757
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.4530842618551105
purpose: []
