name: EZPolitics
favicon: null
layout_spectrum: 0.5838228759821504
typography_spectrum: 0.21689759846776724
title: 'Politics Made EZ!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#ba0000'
    - '#2b24ad'
    - '#6772f0'
    - '#450000'
  brandStrength: 0.6589674537535757
  lightness: 0.21780909271910787
  saturation: 0.1866078171879053
  rhythmicContrast: 0.4530842618551105
purpose: []
